apiVersion: v1
kind: PersistentVolume
metadata:
  name: glance-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_GLANCE_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-unified-pvc
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: glance-pv
  resources:
    requests:
      storage: 5Gi
