authentik:


  error_reporting:
    enabled: false



server:
  env:
    - name: AUTHENTIK_WEB__WORKERS
      value: "1"
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - auth.${BASE_DOMAIN}
    tls:
      - hosts:
          - auth.${BASE_DOMAIN}
        secretName: auth-tls-secret
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod-cf

worker:
  env:
    - name: AUTHENTIK_WORKER__THREADS
      value: "1"

postgresql:
  enabled: true
