apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
  local:
    path: /var/lib/rancher/k3s/storage/pvc-bf050742-3c03-443a-bf79-bde6a7621507_infra_data-authentik-postgresql-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kubertwo
