apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-authentik-postgresql-0
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeName: authentik-postgres-pv
