apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: [ ReadWriteMany ]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_TRILIUM_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-pvc
  namespace: personal
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ""
  volumeName: trilium-pv
  resources:
    requests:
      storage: 5Gi
