apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-sync-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_ACTUAL_BUDGET_SYNC_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-sync-pvc
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: actual-budget-sync-pv
  resources:
    requests:
      storage: 1Gi
