apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphite-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.10.10.200
    path: /mnt/ghostdata/ghostsilo/99_System/K8S-Data/graphite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphite-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: graphite-pv
  resources:
    requests:
      storage: 10Gi
