apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_WALLABAG_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-pvc
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: wallabag-pv
  resources:
    requests:
      storage: 5Gi
