apiVersion: v1
kind: PersistentVolume
metadata:
  name: lazylibrarian-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_LAZYLIBRARIAN_CONFIG_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lazylibrarian-config-pvc
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: lazylibrarian-config-pv
  resources:
    requests:
      storage: 2Gi
