[docker_vms]
ghostgpu    ansible_host=10.10.10.111
nextcloud   ansible_host=10.10.10.113
utility     ansible_host=10.10.10.114
ghostmedia  ansible_host=10.10.10.115

[k3s_workers]
kubeone     ansible_host=10.10.10.100
# homeservertoo ansible_host=  # fill in IP

[k3s_master]
# k3s-master ansible_host=  # fill in IP

[linux:children]
docker_vms
k3s_workers
k3s_master

[all:vars]
ansible_python_interpreter=/usr/bin/python3
