[docker_vms]
ghostgpu        ansible_host=10.10.10.111
security        ansible_host=10.10.10.112
nextcloud       ansible_host=10.10.10.113
utility         ansible_host=10.10.10.114
ghostmedia      ansible_host=10.10.10.115

[k3s_workers]
kuberone        ansible_host=10.10.10.100
kubertwo        ansible_host=10.10.10.101

[k3s_master]
kuber           ansible_host=10.10.10.99

[linux:children]
docker_vms
k3s_workers
k3s_master

[all:vars]
ansible_python_interpreter=/usr/bin/python3
